name: D compatibility branch

on:
  workflow_dispatch:
  push:
    branches:
      - d-compat/**

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    uses: discourse/.github/.github/workflows/plugin-tests.yml@main
    secrets: inherit
