name: Metadata

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout head repository
        uses: actions/checkout@v2

      - name: Store head version
        run: |
          sed -n -e 's/^.*version: /head_version=/p' plugin.rb >> $GITHUB_ENV

      - name: Checkout base repository
        uses: actions/checkout@v2
        with:
          ref: "${{ github.base_ref }}"

      - name: Store base version
        run: |
          sed -n -e 's/^.*version: /base_version=/p' plugin.rb >> $GITHUB_ENV

      - name: Check version
        shell: ruby {0}
        run: |
          require "rubygems/version"

          head_version = Gem::Version.new(ENV.fetch("head_version"))
          base_version = Gem::Version.new(ENV.fetch("base_version"))

          abort "Head version is equal to or lower than base version." if head_version <= base_version
